language: python
python:
  - "2.6"
  - "2.7"
  - "nightly"
matrix:
  allow_failures:
    - python: "nightly"
  fast_finish: true

# Route build to VM-based infrastructure, so we can create directories under
# /var (as per the setup.py script)
sudo: requried

# Cache the dependencies installed by pip
cache: pip
# Avoid pip log from affecting cache
before_cache: rm -fv ~/.cache/pip/log/debug.log

before_install:
  # Make directories as root. We have to do this here because we can't run
  # python setup.py install as root due to a conflict between sudo and Travis
  # virtualenvs.
  - sudo mkdir -p /var/log/apel /var/run/apel /etc/apel /usr/share/apel /etc/logrotate.d
  # Make them read write and executable by all so the setup script can be
  # ran as a user other than root.
  - sudo chmod a+rwx /var/log/apel /var/run/apel /etc/apel /usr/share/apel /etc/logrotate.d

install:
  # Doing this because pip install seems not to install test requirements
  # We need to alter PYTHONPATH because the setup.py script does not install
  # bin as a python package.
  - export PYTHONPATH=$PYTHONPATH:`pwd -P`
  # As coveralls is only a requirement for running the unitests on Travis,
  # install coveralls now.
  - pip install coveralls

# Commands that prepare things for the test
before_script:
  - cd test

script: coverage run --branch --source=../apel,../bin ../setup.py test

after_success: coveralls
